// Story Bible generation (story-bible spec R1, R2.3, R6 — design §2).
//
// The bible is a second, larger planning artifact generated by a dedicated
// background LLM call that races turn 1 behind the opening cinematic: a key
// registry, a lock plan, a cast sheet, a twist bank, and ending requirement
// sketches. Per-turn prompts then gate only against planned or already-granted
// keys, so a locked door whose key no path grants becomes impossible by
// construction (R4).
//
// This module mirrors `summarizer.ts` end to end (task SB-S2):
//
//   1. `buildStoryBiblePrompt` / `buildStoryBibleRefreshPrompt` (pure) —
//      prompt bodies from the same premise/seed inputs as the turn-1 request.
//      Pure + exported so unit tests pin the format.
//   2. `generateStoryBible` (action) — scheduled non-blocking from
//      `createSave`'s llm fork (game.ts). Provider fan-out in the
//      summarizer's cheap-model order (DeepSeek → Anthropic → Gemini); the
//      Gemini path is grammar-constrained by `STORY_BIBLE_RESPONSE_SCHEMA`.
//      Parse → `validateProposedBible` → per-string `evaluateTextPolicy`
//      neutralization (R2.3) → `_setStoryBible`. Every failure path is
//      silent: at most ONE retry (R1.4), then status:"failed" and the save
//      plays bible-less forever (BC9). There is deliberately NO deterministic
//      fallback — a fabricated bible is worse than no bible.
//   3. `refreshStoryBible` (action, R6) — scheduled once per act boundary
//      from the turn mutation. The action only makes the LLM call; the merge
//      (`mergeBibleRefresh`) runs inside `_applyBibleRefresh` against the
//      row's CURRENT bible so a turn that landed mid-flight can't be
//      clobbered. A failed refresh keeps the old bible silently.
//   4. Internal mutations — the actions' only DB surface (SB2):
//      `_markStoryBibleGenerating` / `_setStoryBible` / `_markStoryBibleRetry`
//      / `_markStoryBibleFailed` / `_applyBibleRefresh`.
//
// Also home to the pure registry-event fold (`foldRegistryEvents`) that the
// turn mutation applies to the bible row IN THE SAME MUTATION as the state
// write (SB4/R2.1), and `readStoryBible`, the tolerant row→engine-type reader.

import { v } from "convex/values";
import { actionGeneric, internalMutationGeneric, queryGeneric } from "convex/server";

import {
  BIBLE_REGISTRY_CAP,
  mergeBibleRefresh,
  validateProposedBible,
  type BibleCast,
  type BibleProtagonist,
  type BibleDoor,
  type BibleKey,
  type BibleTwist,
  type RegistryEvent,
  type StoryBible,
} from "@cyoa/engine";
import type { ContentPolicyContext } from "@cyoa/shared";

import { buildAnalyticsEvent, type AnalyticsMetricName } from "../analytics";
import { evaluateTextPolicy } from "../contentPolicy";
import { loadAndAuthorizeAccount } from "../lib/authz";
import { AppError } from "../lib/errors";
import {
  appendPath,
  postJson,
  readEnv,
  readTimeoutMs,
} from "./httpClient";
import { fireworksModelId, readFireworksConfig } from "./fireworks";
import { STORY_BIBLE_RESPONSE_SCHEMA } from "./responseSchema";

const accountIdValidator = v.id("accounts");
const saveIdValidator = v.id("saves");

// Output budget: the bible is a compact structured object (≈2-3 KB JSON) —
// smaller than one scene call (NFR cost envelope). 1600 tokens covers the
// 12-key worst case with headroom.
const BIBLE_MAX_OUTPUT_TOKENS = 1_600;

// Premise excerpt cap — same rationale as the summarizer's excerpt cap: the
// model only needs enough of the premise to plan nouns, and the call stays
// cheap.
export const BIBLE_PREMISE_MAX_CHARS = 1_200;

/** At most ONE retry of the generation call (R1.4). */
export const BIBLE_MAX_RETRIES = 1;

export type StoryBiblePromptInput = {
  premise: string;
  storyTitle: string;
  storyTone?: string | undefined;
};

/**
 * Build the bible-generation prompt. Pure + exported so the unit test pins
 * the format (the prompt is part of the contract with the planning LLM).
 * Seeded from the same premise/seed inputs as the turn-1 scene request (R1.1)
 * so the plan and the opening scene describe the same world.
 */
export function buildStoryBiblePrompt(input: StoryBiblePromptInput): string {
  const premise =
    (input.premise || "").replace(/\s+/g, " ").trim().slice(0, BIBLE_PREMISE_MAX_CHARS) ||
    "(no explicit premise — invent a grounded, specific world)";
  const title = (input.storyTitle || "").trim() || "an untitled interactive story";
  const toneLine = input.storyTone ? `Tone: ${input.storyTone.trim()}.` : null;
  return [
    `You are the story planner for an interactive story called "${title}". Before the first scene is written, you plan the story's NOUNS — the keys, doors, people, and twists the narrator will pay off over 10-15 scenes. The reader NEVER sees this plan; the narrator uses it as gravity, not rails.`,
    toneLine,
    "",
    `Story premise: """${premise}"""`,
    "",
    "Output a single JSON object with EXACTLY these fields:",
    '- "protagonist": { "name": string (≤80), "gender": string (≤40), "pronouns": string (≤40, e.g. "she/her"), "appearance": 2-6 short strings (≤60 each — hair, build, age-look, signature dress), "voice": string (≤120, how they speak and carry themselves) }. This is the ONE person the reader plays. Fix it now; it must NEVER change over the whole story.',
    '- "keyRegistry": 6-12 entries { "id": kebab-slug (≤48), "label": string (≤80, the item as the reader will meet it), "opensHint": string (≤120, what it will unlock or enable), "surfaceBand": "early" | "mid" | "late" (when it should first appear) }. These are the ONLY items the story plans to gate on — concrete, findable objects (a key, a token, a writ, a name), not abstractions.',
    '- "lockPlan": 2-5 entries { "id": kebab-slug (≤48), "label": string (≤80, the door/obstacle), "keyId": MUST be one of the keyRegistry ids, "gateBand": "mid" | "late", "note": string (≤120) }. Every door\'s key must surface in an earlier-or-equal band than its gate.',
    '- "cast": 2-5 entries { "id": kebab-slug (≤48), "label": string (≤80, name + role), "want": string (≤120), "secret": string (≤120), "bondHint": string (≤120, how the reader might earn or break their trust), "appearance": string (≤120, what the reader SEES — build, hair, dress, age-look) }.',
    '- "twists": 2-4 entries { "id": kebab-slug (≤48), "label": string (≤80), "precondition": string (≤120, what must be true before this twist can fire) }.',
    '- "endingHints": 2-4 entries { "endingId": kebab-slug (≤48, a likely ending), "requires": string (≤160, sketch of what reaching it takes) }.',
    '- "motifs": 3-6 strings (≤40 each) — imagery and tone anchors.',
    "",
    "Rules:",
    "1. Everything must be SPECIFIC to this premise — no generic 'ancient key opens ancient door'.",
    "2. Keys are pinned to conditions and bands, never to scenes — the reader may wander anywhere and the plan must survive.",
    "3. Spread surfaceBand across early/mid/late so the story always has a next thing to find.",
    "4. Output ONLY the JSON object. No markdown fences, no preamble, no commentary.",
  ]
    .filter((line): line is string => line !== null)
    .join("\n");
}

export type StoryBibleRefreshPromptInput = {
  premise: string;
  storySummary: string;
  act: number;
  /** The current bible (with consumption state) the model may revise. */
  bible: StoryBible;
};

/**
 * Build the act-boundary refresh prompt (R6.1). Carries the current bible +
 * consumption state + the rolling story summary; the model may relocate or
 * retire unconsumed entries and add ≤2 new registry keys. The merge rules
 * (`mergeBibleRefresh`) enforce immutability server-side regardless of what
 * comes back — this prompt only sets expectations.
 */
export function buildStoryBibleRefreshPrompt(input: StoryBibleRefreshPromptInput): string {
  const premise =
    (input.premise || "").replace(/\s+/g, " ").trim().slice(0, BIBLE_PREMISE_MAX_CHARS) ||
    "(no explicit premise)";
  const summary = (input.storySummary || "").trim() || "(no summary yet)";
  const currentPlan = JSON.stringify({
    keyRegistry: input.bible.keyRegistry.map(({ id, label, opensHint, surfaceBand, status }) => ({
      id,
      label,
      opensHint,
      surfaceBand,
      status,
    })),
    lockPlan: input.bible.lockPlan.map(({ id, label, keyId, gateBand, note, status }) => ({
      id,
      label,
      keyId,
      gateBand,
      note,
      status,
    })),
    twists: input.bible.twists.map(({ id, label, precondition, status }) => ({
      id,
      label,
      precondition,
      status,
    })),
  });
  return [
    `You are the story planner revising a mid-flight plan at the start of act ${input.act}. The reader's actual path may have made parts of the original plan stale — relocate or retire what no longer fits; keep what still works.`,
    "",
    `Story premise: """${premise}"""`,
    "",
    "Story so far (canonical):",
    summary,
    "",
    "Current plan (entries with status other than planned/pending are CONSUMED — you cannot change them):",
    currentPlan,
    "",
    "Output a single JSON object in the SAME shape as the current plan's sections plus \"cast\", \"endingHints\", and \"motifs\" (they may be empty arrays):",
    "1. Re-emit every keyRegistry / lockPlan / twist entry you want to KEEP, by the same id (you may update its label/hint/band). An omitted unconsumed entry is retired.",
    "2. You may add AT MOST 2 new keyRegistry entries.",
    "3. Never remove or alter a consumed (promised/granted/opened/fired) entry — it already happened.",
    "4. Output ONLY the JSON object. No markdown fences, no preamble, no commentary.",
  ].join("\n");
}

/**
 * Extract a JSON object from a raw LLM reply: strips markdown fences and
 * anything before/after the outermost braces. Returns null (never throws) on
 * unparseable text — the caller treats null as a failed attempt (BC5).
 */
export function extractBibleJson(raw: string): unknown {
  if (!raw) return null;
  let text = raw.trim();
  text = text.replace(/^```(?:json|\w+)?\s*([\s\S]*?)\s*```$/m, "$1").trim();
  const start = text.indexOf("{");
  const end = text.lastIndexOf("}");
  if (start === -1 || end <= start) return null;
  try {
    return JSON.parse(text.slice(start, end + 1));
  } catch {
    return null;
  }
}

// Conservative policy context for bible text. The bible is server-only
// planning text (never shown to the reader), but R2.3 still gates every
// string through the classifier before persistence; the strictest surface
// (no mature allowance) keeps the check independent of the reader's account
// state so the action stays pure of DB reads (SB2).
const BIBLE_POLICY_CONTEXT: ContentPolicyContext = {
  surface: "generation",
  entitlementTier: "free",
  matureContentEnabled: false,
};

/** Neutral placeholder for a policy-blocked bible string (R2.3). */
const NEUTRALIZED = "";

function policySafe(text: string, context: ContentPolicyContext): string {
  const trimmed = (text ?? "").trim();
  if (trimmed.length === 0) return trimmed;
  const policy = evaluateTextPolicy({ text: trimmed, context });
  return policy.action === "allow" ? trimmed : NEUTRALIZED;
}

/**
 * Run every human-readable bible string through `evaluateTextPolicy` and
 * neutralize blocked ones (R2.3) — never a failure. Slug ids are left alone
 * (they are engine-generated kebab tokens). Labels fall back to the id so an
 * entry never loses its handle. Pure; returns a new bible.
 */
export function sanitizeBibleStrings(
  bible: StoryBible,
  context: ContentPolicyContext = BIBLE_POLICY_CONTEXT,
): StoryBible {
  const safeLabel = (label: string, id: string): string => {
    const safe = policySafe(label, context);
    return safe.length > 0 ? safe : id;
  };
  const keyRegistry: BibleKey[] = bible.keyRegistry.map((key) => ({
    ...key,
    label: safeLabel(key.label, key.id),
    opensHint: policySafe(key.opensHint, context),
  }));
  const lockPlan: BibleDoor[] = bible.lockPlan.map((door) => ({
    ...door,
    label: safeLabel(door.label, door.id),
    note: policySafe(door.note, context),
  }));
  const cast: BibleCast[] = bible.cast.map((member) => ({
    ...member,
    label: safeLabel(member.label, member.id),
    want: policySafe(member.want, context),
    secret: policySafe(member.secret, context),
    bondHint: policySafe(member.bondHint, context),
  }));
  const twists: BibleTwist[] = bible.twists.map((twist) => ({
    ...twist,
    label: safeLabel(twist.label, twist.id),
    precondition: policySafe(twist.precondition, context),
  }));
  const endingHints = bible.endingHints.map((hint) => ({
    ...hint,
    requires: policySafe(hint.requires, context),
  }));
  const motifs = bible.motifs
    .map((motif) => policySafe(motif, context))
    .filter((motif) => motif.length > 0);
  return { ...bible, keyRegistry, lockPlan, cast, twists, endingHints, motifs };
}

/**
 * Tolerant reader for the persisted `story_bibles.bible` JSON → engine
 * StoryBible. We wrote the value through `validateProposedBible`, so this is
 * shape-insurance, not validation: a row that doesn't minimally look like a
 * bible reads as null (bible-less behavior, BC9) rather than throwing inside
 * a turn mutation.
 */
export function readStoryBible(raw: unknown): StoryBible | null {
  if (typeof raw !== "object" || raw === null) return null;
  const obj = raw as Record<string, unknown>;
  if (!Array.isArray(obj.keyRegistry)) return null;
  // The protagonist identity (character-consistency §1) is the load-bearing
  // anchor against mid-story gender/appearance drift and MUST survive the
  // round-trip: this reader runs both when persisting the freshly-generated
  // bible (`_setStoryBible`) and when reading the stored row back into the
  // engine each turn. Omitting it here silently strips the field on write AND
  // on every read, defeating the whole prose+image fix. Carried through as an
  // opaque object (validateProposedBible already clamped it at generation);
  // absent/malformed → field omitted (legacy-tolerant, BC9).
  const protagonist =
    typeof obj.protagonist === "object" && obj.protagonist !== null
      ? (obj.protagonist as BibleProtagonist)
      : undefined;
  return {
    keyRegistry: obj.keyRegistry as BibleKey[],
    lockPlan: Array.isArray(obj.lockPlan) ? (obj.lockPlan as BibleDoor[]) : [],
    cast: Array.isArray(obj.cast) ? (obj.cast as BibleCast[]) : [],
    twists: Array.isArray(obj.twists) ? (obj.twists as BibleTwist[]) : [],
    endingHints: Array.isArray(obj.endingHints)
      ? (obj.endingHints as StoryBible["endingHints"])
      : [],
    motifs: Array.isArray(obj.motifs) ? (obj.motifs as string[]) : [],
    ...(protagonist ? { protagonist } : {}),
    source: "llm",
    version: 1,
  };
}

/**
 * Fold a turn's `RegistryEvent[]` into the bible (SB4/R2.1). The engine never
 * mutates its registry input — all consumption-state changes flow out as
 * events, and the turn mutation applies this fold to the bible row IN THE
 * SAME MUTATION as the state write, so bible state can never disagree with
 * save state. Pure; returns a new bible.
 */
export function foldRegistryEvents(bible: StoryBible, events: RegistryEvent[]): StoryBible {
  if (events.length === 0) return bible;
  const keyRegistry: BibleKey[] = bible.keyRegistry.map((key) => ({ ...key }));
  const lockPlan: BibleDoor[] = bible.lockPlan.map((door) => ({ ...door }));
  for (const event of events) {
    switch (event.kind) {
      case "promise": {
        const key = keyRegistry.find((candidate) => candidate.id === event.keyId);
        if (key && key.status === "planned") {
          key.status = "promised";
          key.promisedAtTurn = event.turn;
        }
        break;
      }
      case "adopt": {
        if (
          !keyRegistry.some((candidate) => candidate.id === event.key.id) &&
          keyRegistry.length < BIBLE_REGISTRY_CAP
        ) {
          keyRegistry.push({ ...event.key });
        }
        break;
      }
      case "granted": {
        const key = keyRegistry.find((candidate) => candidate.id === event.keyId);
        if (key && key.status !== "retired" && key.status !== "granted") {
          key.status = "granted";
          key.grantedAtTurn = event.turn;
        }
        break;
      }
      case "seeded": {
        const key = keyRegistry.find((candidate) => candidate.id === event.keyId);
        if (key) key.seeded = true;
        break;
      }
      case "door_opened": {
        const door = lockPlan.find((candidate) => candidate.id === event.doorId);
        if (door && door.status === "planned") door.status = "opened";
        break;
      }
      case "phantom_unlock":
        // Analytics-only — nothing to fold (the gate was auto-unlocked).
        break;
    }
  }
  return { ...bible, keyRegistry, lockPlan };
}

// =============================================================================
// Doors journal (DOORS-JOURNAL — the reader-facing half of the fetch-quest
// loop; core-read-loop Req 22 companion surface). The bible itself NEVER
// reaches the client (R2.2); this projection is the single deliberate
// exception, and it surfaces ONLY what the reader has already seen on screen
// (BC10):
//
//   - a key becomes journal-visible exactly when its gate RENDERED locked —
//     that is the moment the fold stamped `promisedAtTurn` (promise/adopt
//     events, see `foldRegistryEvents`). Planned-but-never-promised registry
//     entries are invisible.
//   - `state` tracks what the reader has lived: "teased" (the locked door is
//     on screen, key still out there), "key-in-hand" (the granted/seeded key
//     has since landed in inventory — the `granted` fold), "opened" (the
//     door-open event fired).
//
// NEVER projected: registry keys not yet gated on-screen, surfaceBands /
// gateBands, lockPlan doors not yet rendered, hints for unseen keys, twists,
// ending hints, motifs, ids, or any turn/consumption bookkeeping.
// =============================================================================

export type DoorsJournalEntry = {
  /** The door as the reader met it (lock label, or the key's label for an ad-hoc gate). */
  label: string;
  /** The tease the reader saw (the seen key's opensHint); may be empty. */
  hint: string;
  state: "teased" | "key-in-hand" | "opened";
};

/**
 * Pure bible → journal projection. Exported for the spoiler tests — the test
 * asserts the forbidden fields above can never appear in the output shape.
 * Tolerant: a null bible (bible-less save, BC9) projects an empty journal.
 */
export function projectDoorsJournal(bible: StoryBible | null): DoorsJournalEntry[] {
  if (!bible) return [];
  const entries: DoorsJournalEntry[] = [];
  const coveredDoorIds = new Set<string>();
  for (const key of bible.keyRegistry) {
    // BC10 "seen" gate: only keys whose gate rendered locked on-screen carry
    // `promisedAtTurn` (stamped by the promise/adopt fold). Everything else
    // is an unfired plan — invisible.
    if (typeof key.promisedAtTurn !== "number" || key.status === "retired") continue;
    const doors = bible.lockPlan.filter(
      (door) => door.keyId === key.id && door.status !== "retired",
    );
    for (const door of doors) coveredDoorIds.add(door.id);
    const opened = doors.some((door) => door.status === "opened");
    const state: DoorsJournalEntry["state"] = opened
      ? "opened"
      : key.status === "granted"
        ? "key-in-hand"
        : "teased";
    entries.push({ label: doors[0]?.label ?? key.label, hint: key.opensHint, state });
  }
  // A door that OPENED without its key ever being promised (the reader already
  // held the key when the gate first rendered): the walk-through happened on
  // screen so the door's label is reader-seen — but its key was never teased,
  // so no hint rides along (BC10: no opensHints for unseen keys).
  for (const door of bible.lockPlan) {
    if (door.status !== "opened" || coveredDoorIds.has(door.id)) continue;
    entries.push({ label: door.label, hint: "", state: "opened" });
  }
  return entries;
}

/**
 * Reader-facing doors journal for a save (DOORS-JOURNAL). Auth mirrors
 * `game:getCurrentScene` (own the save + valid session). Bible-less /
 * not-ready saves project an empty journal — the client renders nothing
 * (zero-state invisible, BC9).
 */
export const getDoorsJournal = queryGeneric({
  args: {
    accountId: accountIdValidator,
    saveId: saveIdValidator,
    guestTokenHash: v.optional(v.string()),
  },
  handler: async (ctx, args): Promise<DoorsJournalEntry[]> => {
    const saveDoc = await ctx.db.get(args.saveId);
    if (!saveDoc) throw new AppError("save_not_found");
    if (String((saveDoc as { accountId?: unknown }).accountId) !== String(args.accountId)) {
      throw new AppError("save_forbidden");
    }
    await loadAndAuthorizeAccount(ctx, args.accountId, args.guestTokenHash);
    const row = await loadBibleRow(ctx, args.saveId);
    if (!row || row.status !== "ready") return [];
    return projectDoorsJournal(readStoryBible(row.bible));
  },
});

// =============================================================================
// Provider fan-out (mirrors summarizer.ts callSummarizer — cheap-model order).
// =============================================================================

type BibleProviderName = "fireworks" | "anthropic" | "vertex";

type BibleProviderResult = {
  provider: BibleProviderName;
  text: string;
};

/**
 * Call the cheapest configured LLM with a bible prompt. Order matches the
 * summarizer: Fireworks (cheap model) → Anthropic → Gemini. The Gemini path
 * passes `STORY_BIBLE_RESPONSE_SCHEMA` so output is grammar-constrained JSON.
 * Returns null when every configured path failed or none is configured —
 * NO deterministic fallback (R1.4: the save plays bible-less instead).
 *
 * Exported so the unit test can pin the model selection (which env → which
 * model id) without standing up the whole action.
 */
export async function callStoryBibleModel(prompt: string): Promise<BibleProviderResult | null> {
  // 1. Fireworks cheap model — the background cheap path (design §1.4).
  //    Replaces the old direct-DeepSeek leg (whose hardcoded `deepseek-chat`
  //    alias is deprecated); Fireworks serves DeepSeek-V3 as its cheap model.
  const fireworks = readFireworksConfig();
  if (fireworks.apiKey) {
    try {
      const response = await postJson({
        url: appendPath(fireworks.baseUrl, "/chat/completions"),
        timeoutMs: fireworks.timeoutMs,
        headers: { authorization: `Bearer ${fireworks.apiKey}` },
        body: {
          model: fireworksModelId("cheap"),
          temperature: 0.6,
          max_tokens: BIBLE_MAX_OUTPUT_TOKENS,
          response_format: { type: "json_object" },
          messages: [
            {
              role: "system",
              content:
                "You are a story planner. You output only a single JSON object, never prose or markdown.",
            },
            { role: "user", content: prompt },
          ],
        },
      });
      const text = extractDeepSeekText(response);
      if (text.trim().length > 0) return { provider: "fireworks", text };
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      console.warn(`[storyBible] fireworks failed: ${message.slice(0, 240)}`);
    }
  }

  // 2. Anthropic — a REAL Haiku id via ANTHROPIC_BIBLE_MODEL (NOT the shared
  //    ANTHROPIC_MODEL, which silently upgrades this cheap background call to
  //    Sonnet). Default `claude-haiku-4-5` (the old `claude-haiku-4-6` default
  //    did not exist and silently upgraded to Sonnet).
  const anthropicKey = readEnv("ANTHROPIC_API_KEY");
  if (anthropicKey) {
    try {
      const baseUrl = readEnv("ANTHROPIC_BASE_URL") ?? "https://api.anthropic.com";
      const response = await postJson({
        url: appendPath(baseUrl, "/v1/messages"),
        timeoutMs: readTimeoutMs(),
        headers: {
          "anthropic-version": "2023-06-01",
          "x-api-key": anthropicKey,
        },
        body: {
          model: readEnv("ANTHROPIC_BIBLE_MODEL") ?? "claude-haiku-4-5",
          max_tokens: BIBLE_MAX_OUTPUT_TOKENS,
          temperature: 0.6,
          messages: [{ role: "user", content: prompt }],
        },
      });
      const text = extractAnthropicText(response);
      if (text.trim().length > 0) return { provider: "anthropic", text };
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      console.warn(`[storyBible] anthropic failed: ${message.slice(0, 240)}`);
    }
  }

  // 3. Gemini — grammar-constrained by the wire schema (design §2). The
  //    bible schema is small and flat (no anyOf), so unlike the scene path
  //    (vertex.ts deliberately avoids responseSchema there) it is safe here.
  const geminiKey = readEnv("GEMINI_API_KEY");
  if (geminiKey) {
    try {
      const model = readEnv("GEMINI_TEXT_MODEL") ?? "gemini-2.5-flash";
      const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${geminiKey}`;
      const response = await postJson({
        url,
        timeoutMs: readTimeoutMs(),
        headers: {},
        body: {
          contents: [{ role: "user", parts: [{ text: prompt }] }],
          generationConfig: {
            temperature: 0.6,
            maxOutputTokens: BIBLE_MAX_OUTPUT_TOKENS,
            responseMimeType: "application/json",
            responseSchema: STORY_BIBLE_RESPONSE_SCHEMA,
            // Same fix as the summarizer/scene paths: without this the model
            // burns the whole budget on hidden reasoning.
            thinkingConfig: { thinkingLevel: "minimal" },
          },
        },
      });
      const text = extractGeminiText(response);
      if (text.trim().length > 0) return { provider: "vertex", text };
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      console.warn(`[storyBible] gemini failed: ${message.slice(0, 240)}`);
    }
  }

  return null;
}

function extractDeepSeekText(response: unknown): string {
  const choice = (response as { choices?: Array<{ message?: { content?: string } }> })
    .choices?.[0];
  return choice?.message?.content ?? "";
}

function extractAnthropicText(response: unknown): string {
  const content = (response as { content?: Array<{ type?: string; text?: string }> }).content;
  if (!Array.isArray(content)) return "";
  const block = content.find((b) => b?.type === "text" && typeof b.text === "string");
  return (block?.text ?? "").toString();
}

function extractGeminiText(response: unknown): string {
  const candidate = (
    response as { candidates?: Array<{ content?: { parts?: Array<{ text?: string }> } }> }
  ).candidates?.[0];
  const parts = candidate?.content?.parts ?? [];
  return parts.map((p) => (typeof p.text === "string" ? p.text : "")).join("").trim();
}

// =============================================================================
// Actions (SB2: no direct DB access — persistence via internal mutations).
// =============================================================================

export const generateStoryBible = actionGeneric({
  args: {
    saveId: saveIdValidator,
    accountId: accountIdValidator,
    premise: v.string(),
    storyTitle: v.string(),
    storyTone: v.optional(v.string()),
    /** Retry counter — 0 on the first attempt; ≤ BIBLE_MAX_RETRIES (R1.4). */
    attempt: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    const attempt = args.attempt ?? 0;
    // Failure-safe end to end: a bible failure must never surface to a reader
    // or block a turn (R1.4) — every path below lands in a silent status.
    try {
      await ctx.runMutation(("llm/storyBible:_markStoryBibleGenerating" as unknown) as any, {
        saveId: args.saveId,
        at: Date.now(),
      });
      const prompt = buildStoryBiblePrompt({
        premise: args.premise,
        storyTitle: args.storyTitle,
        ...(args.storyTone !== undefined ? { storyTone: args.storyTone } : {}),
      });
      const result = await callStoryBibleModel(prompt);
      const proposed = result ? extractBibleJson(result.text) : null;
      const validated = proposed !== null ? validateProposedBible(proposed) : null;
      if (validated === null) {
        return await handleBibleFailure(ctx, args, attempt, result === null ? "no_provider" : "unsalvageable");
      }
      // R2.3: neutralize policy-blocked strings — never a failure.
      const sanitized = sanitizeBibleStrings(validated);
      await ctx.runMutation(("llm/storyBible:_setStoryBible" as unknown) as any, {
        saveId: args.saveId,
        accountId: args.accountId,
        bible: sanitized,
        retried: attempt > 0,
        at: Date.now(),
      });
      console.log(
        `[storyBible] ready save=${args.saveId} provider=${result?.provider} keys=${sanitized.keyRegistry.length} doors=${sanitized.lockPlan.length} attempt=${attempt}`,
      );
      return {
        generated: true,
        keys: sanitized.keyRegistry.length,
        provider: result?.provider,
      } as const;
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      console.warn(
        `[storyBible] unexpected failure save=${args.saveId} attempt=${attempt} error=${message.slice(0, 240)}`,
      );
      try {
        return await handleBibleFailure(ctx, args, attempt, "exception");
      } catch {
        return { generated: false, reason: "exception" } as const;
      }
    }
  },
});

/**
 * Shared failure path for `generateStoryBible`: reschedule once (R1.4), else
 * mark the row failed — the save plays bible-less forever under exactly
 * today's behavior (BC9).
 */
async function handleBibleFailure(
  ctx: {
    runMutation: (ref: any, args: any) => Promise<any>;
    scheduler: { runAfter: (ms: number, ref: any, args: any) => Promise<any> };
  },
  args: {
    saveId: string;
    accountId: string;
    premise: string;
    storyTitle: string;
    storyTone?: string | undefined;
  },
  attempt: number,
  reason: string,
): Promise<{ generated: false; reason: string; retried: boolean }> {
  if (attempt < BIBLE_MAX_RETRIES) {
    await ctx.runMutation(("llm/storyBible:_markStoryBibleRetry" as unknown) as any, {
      saveId: args.saveId,
      at: Date.now(),
    });
    await ctx.scheduler.runAfter(0, ("llm/storyBible:generateStoryBible" as unknown) as any, {
      saveId: args.saveId,
      accountId: args.accountId,
      premise: args.premise,
      storyTitle: args.storyTitle,
      ...(args.storyTone !== undefined ? { storyTone: args.storyTone } : {}),
      attempt: attempt + 1,
    });
    console.warn(`[storyBible] retrying save=${args.saveId} reason=${reason}`);
    return { generated: false, reason, retried: true };
  }
  await ctx.runMutation(("llm/storyBible:_markStoryBibleFailed" as unknown) as any, {
    saveId: args.saveId,
    at: Date.now(),
  });
  console.warn(`[storyBible] failed permanently save=${args.saveId} reason=${reason}`);
  return { generated: false, reason, retried: false };
}

export const refreshStoryBible = actionGeneric({
  args: {
    saveId: saveIdValidator,
    accountId: accountIdValidator,
    act: v.number(),
    premise: v.string(),
    storySummary: v.string(),
    /** Current bible snapshot for PROMPT context only — the merge in
     * `_applyBibleRefresh` re-reads the row so a mid-flight turn can't be
     * clobbered. */
    bible: v.any(),
  },
  handler: async (ctx, args) => {
    try {
      const current = readStoryBible(args.bible);
      if (!current) return { refreshed: false, reason: "no_bible" } as const;
      const prompt = buildStoryBibleRefreshPrompt({
        premise: args.premise,
        storySummary: args.storySummary,
        act: args.act,
        bible: current,
      });
      const result = await callStoryBibleModel(prompt);
      if (!result) return { refreshed: false, reason: "no_provider" } as const;
      const proposed = extractBibleJson(result.text);
      if (proposed === null) return { refreshed: false, reason: "unparseable" } as const;
      await ctx.runMutation(("llm/storyBible:_applyBibleRefresh" as unknown) as any, {
        saveId: args.saveId,
        accountId: args.accountId,
        act: args.act,
        proposed,
        at: Date.now(),
      });
      return { refreshed: true } as const;
    } catch (err) {
      // A failed refresh keeps the old bible silently (R6.1).
      const message = err instanceof Error ? err.message : String(err);
      console.warn(
        `[storyBible] refresh failed save=${args.saveId} act=${args.act} error=${message.slice(0, 240)}`,
      );
      return { refreshed: false, reason: "exception" } as const;
    }
  },
});

// =============================================================================
// Internal mutations — the actions' entire DB surface (SB2).
// =============================================================================

async function loadBibleRow(
  ctx: { db: any },
  saveIdValue: string,
): Promise<Record<string, unknown> | null> {
  return await ctx.db
    .query("story_bibles")
    .withIndex("by_saveId", (q: any) => q.eq("saveId", saveIdValue))
    .first();
}

/** Best-effort `analytics_events` insert (fire-and-forget, R4.6 pattern). */
async function insertBibleAnalytics(
  ctx: { db: { insert: (table: string, doc: any) => Promise<any> } },
  input: {
    eventName: string;
    accountId?: string | undefined;
    saveId: string;
    storyId?: string | undefined;
    turnNumber?: number | undefined;
    payload?: Record<string, unknown>;
    now: number;
  },
): Promise<void> {
  try {
    await ctx.db.insert(
      "analytics_events",
      buildAnalyticsEvent({
        eventName: input.eventName as AnalyticsMetricName,
        ...(input.accountId ? { accountId: input.accountId } : {}),
        saveId: input.saveId,
        ...(input.storyId ? { storyId: input.storyId } : {}),
        ...(input.turnNumber === undefined ? {} : { turnNumber: input.turnNumber }),
        payload: input.payload ?? {},
        createdAt: input.now,
      }),
    );
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.warn(
      `[storyBible] analytics insert failed event=${input.eventName} error=${message.slice(0, 200)}`,
    );
  }
}

export const _markStoryBibleGenerating = internalMutationGeneric({
  args: { saveId: saveIdValidator, at: v.number() },
  handler: async (ctx, args) => {
    const row = await loadBibleRow(ctx, args.saveId);
    // Never regress a terminal status (a late duplicate action run must not
    // resurrect a failed/ready row).
    if (!row || (row.status !== "queued" && row.status !== "generating")) return;
    await ctx.db.patch((row as { _id: any })._id, {
      status: "generating" as const,
      updatedAt: args.at,
    });
  },
});

export const _setStoryBible = internalMutationGeneric({
  args: {
    saveId: saveIdValidator,
    accountId: accountIdValidator,
    bible: v.any(),
    retried: v.boolean(),
    at: v.number(),
  },
  handler: async (ctx, args) => {
    const row = await loadBibleRow(ctx, args.saveId);
    if (!row) return;
    // Idempotency: exactly one bible per save (R1.6) — a duplicate action run
    // must not clobber a bible that already attached / accumulated state.
    if (row.status === "ready") return;
    const bible = readStoryBible(args.bible);
    if (!bible) return;
    await ctx.db.patch((row as { _id: any })._id, {
      status: "ready" as const,
      bible,
      updatedAt: args.at,
    });
    const save = await ctx.db.get(args.saveId as any);
    await insertBibleAnalytics(ctx, {
      eventName: "bible.generated",
      accountId: args.accountId,
      saveId: args.saveId,
      ...(save ? { storyId: (save as { storyId?: string }).storyId } : {}),
      payload: {
        keys: bible.keyRegistry.length,
        doors: bible.lockPlan.length,
        retried: args.retried,
      },
      now: args.at,
    });
  },
});

export const _markStoryBibleRetry = internalMutationGeneric({
  args: { saveId: saveIdValidator, at: v.number() },
  handler: async (ctx, args) => {
    const row = await loadBibleRow(ctx, args.saveId);
    if (!row || row.status === "ready" || row.status === "failed") return;
    await ctx.db.patch((row as { _id: any })._id, {
      status: "queued" as const,
      retryCount: Math.min(
        BIBLE_MAX_RETRIES,
        ((row as { retryCount?: number }).retryCount ?? 0) + 1,
      ),
      updatedAt: args.at,
    });
  },
});

export const _markStoryBibleFailed = internalMutationGeneric({
  args: { saveId: saveIdValidator, at: v.number() },
  handler: async (ctx, args) => {
    const row = await loadBibleRow(ctx, args.saveId);
    if (!row || row.status === "ready") return;
    await ctx.db.patch((row as { _id: any })._id, {
      status: "failed" as const,
      updatedAt: args.at,
    });
  },
});

export const _applyBibleRefresh = internalMutationGeneric({
  args: {
    saveId: saveIdValidator,
    accountId: accountIdValidator,
    act: v.number(),
    proposed: v.any(),
    at: v.number(),
  },
  handler: async (ctx, args) => {
    const row = await loadBibleRow(ctx, args.saveId);
    if (!row || row.status !== "ready") return;
    const current = readStoryBible((row as { bible?: unknown }).bible);
    if (!current) return;
    // Merge against the row's CURRENT bible (not the action's snapshot) so a
    // turn that folded registry events mid-flight is respected. Consumed /
    // granted / promised entries are immutable inside the merge (R6.1/R6.2);
    // an unusable payload returns `current` unchanged — silent keep.
    const merged = mergeBibleRefresh(current, args.proposed);
    if (merged === current) return;
    const sanitized = sanitizeBibleStrings(merged);
    await ctx.db.patch((row as { _id: any })._id, {
      bible: sanitized,
      updatedAt: args.at,
    });
    const beforeIds = new Set(current.keyRegistry.map((key) => key.id));
    const added = sanitized.keyRegistry.filter((key) => !beforeIds.has(key.id)).length;
    const retired =
      sanitized.keyRegistry.filter((key) => key.status === "retired").length -
      current.keyRegistry.filter((key) => key.status === "retired").length;
    const save = await ctx.db.get(args.saveId as any);
    await insertBibleAnalytics(ctx, {
      eventName: "bible.refreshed",
      accountId: args.accountId,
      saveId: args.saveId,
      ...(save ? { storyId: (save as { storyId?: string }).storyId } : {}),
      payload: { act: args.act, added, retired: Math.max(0, retired) },
      now: args.at,
    });
  },
});
