import { LegalDocument, type LegalSection } from "../../components/legal/LegalDocument";

export const TERMS_EFFECTIVE = "Effective — placeholder draft, pending counsel review.";

export const TERMS_SECTIONS: LegalSection[] = [
  {
    heading: "1. The pact you strike",
    body: [
      "By passing the age gate and opening a tale, you agree to these Terms. If you do not agree, close the book — do not use the service.",
      "You must be at least 13 to hold a guest save. Readers under 18 are held to a general-audience shelf; mature controls exist only for verified adults and stay off by default.",
    ],
  },
  {
    heading: "2. Your account and your saves",
    body: [
      "A guest save is bound to a token on your device. Claiming an account attaches an email so your saves travel with you. You are responsible for keeping access to that email.",
      "You may close your account at any time. We honor deletion of your saves and personal range data on request, subject to the retention windows in the Privacy Policy.",
    ],
  },
  {
    heading: "3. What you may create and publish",
    body: [
      "When you publish a tale or seed to the community shelf, you grant us a non-exclusive license to store, display, and stream that content to other readers on the service.",
      "You keep ownership of what you author. You must not publish content you do not have the right to share, and everything you publish is bound by the Content Policy.",
    ],
  },
  {
    heading: "4. AI-generated content",
    body: [
      "Scenes, choices, and endings are generated by AI models in response to your play. Output can be wrong, unexpected, or unlike any real person or event. It is fiction, not advice.",
      "You will not use the generator to attempt to produce content prohibited by the Content Policy, nor to extract, resell, or train competing models on the service's output.",
    ],
  },
  {
    heading: "5. Reporting and moderation",
    body: [
      "Every published tale, community seed, and AI-generated scene carries a Report affordance. We review reports and may hide, revoke, or take down content and suspend accounts that breach these Terms or the Content Policy.",
      "We may act on content proactively where the law or store policy requires it, including removing content and preserving records for the authorities.",
    ],
  },
  {
    heading: "6. Payments and entitlements",
    body: [
      "Subscriptions and one-time entitlements are billed through the platform's store. Prices, renewal, and refund terms are disclosed at purchase and governed by the store's rules.",
      "Consumable credits and spark balances have no cash value and are non-transferable.",
    ],
  },
  {
    heading: "7. Disclaimers and limits",
    body: [
      "The service is provided \"as is\" without warranty. To the fullest extent the law allows, we are not liable for indirect or consequential loss arising from your use of the service or its AI output.",
      "Nothing here limits rights you hold that cannot be waived under the law of your home jurisdiction.",
    ],
  },
  {
    heading: "8. Changes and contact",
    body: [
      "We may update these Terms; material changes will be surfaced in-app before they take effect. Continued use after a change means you accept it.",
      "Questions about these Terms can be sent to the support address listed in the app's settings.",
    ],
  },
];

export default function TermsRoute() {
  return (
    <LegalDocument
      kicker="the covenant"
      title="Terms of Service"
      effective={TERMS_EFFECTIVE}
      intro="The terms below govern the shelf, the saves, and the tales you carry away from it. Read them before the book opens."
      sections={TERMS_SECTIONS}
    />
  );
}
